version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "flake8*"
          - "mypy"
          - "ruff"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
